apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-nginx
  labels:
    app: devops-lab-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-lab-nginx
  template:
    metadata:
      labels:
        app: devops-lab-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
